import jsPDF from 'jspdf';

const MARGIN = 20;
const TEAL = [10, 186, 181];
const GRAY = [60, 60, 60];
const LIGHT_GRAY = [140, 140, 140];

const CTAS_COLORS = {
  1: [229, 62, 62],
  2: [245, 101, 101],
  3: [236, 201, 75],
  4: [46, 155, 218],
  5: [72, 187, 120],
};

const CTAS_NAMES = {
  1: 'Resuscitation',
  2: 'Emergent',
  3: 'Urgent',
  4: 'Less Urgent',
  5: 'Non-Urgent',
};

// Check if we need a new page and add one if so
function ensureSpace(doc, y, needed) {
  const pageHeight = doc.internal.pageSize.getHeight();
  if (y + needed > pageHeight - 30) {
    doc.addPage();
    return MARGIN;
  }
  return y;
}

function heading(doc, text, y) {
  y = ensureSpace(doc, y, 20);
  doc.setTextColor(...TEAL);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(text, MARGIN, y);
  return y + 10;
}

function body(doc) {
  doc.setTextColor(...GRAY);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
}

function writeWrapped(doc, text, y, indent = 0) {
  const maxWidth = doc.internal.pageSize.getWidth() - 2 * MARGIN - indent;
  const lines = doc.splitTextToSize(text, maxWidth);
  const lineHeight = 5;
  const needed = lines.length * lineHeight;
  y = ensureSpace(doc, y, needed);
  doc.text(lines, MARGIN + indent, y);
  return y + needed;
}

function footer(doc) {
  const y = doc.internal.pageSize.getHeight() - 20;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y - 5, doc.internal.pageSize.getWidth() - MARGIN, y - 5);
  doc.setFontSize(7);
  doc.setTextColor(...LIGHT_GRAY);
  const disclaimer = 'DISCLAIMER: This report was generated by Rivr, an AI-powered pre-assessment tool. It is not a medical diagnosis and should be used as supplementary information only. Always seek professional medical advice. In an emergency, call 911.';
  const lines = doc.splitTextToSize(disclaimer, doc.internal.pageSize.getWidth() - 2 * MARGIN);
  doc.text(lines, MARGIN, y);
}

// ── Triage Report (ER / urgent care) ──

export function generateTriageReportPDF({ transcript, assessment, timestamp }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header bar
  doc.setFillColor(26, 35, 50);
  doc.rect(0, 0, pageWidth, 45, 'F');
  doc.setTextColor(...TEAL);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('RIVR', MARGIN, y + 8);
  doc.setFontSize(10);
  doc.setTextColor(160, 174, 192);
  doc.text('AI-Powered Triage Pre-Assessment Report', MARGIN, y + 16);
  doc.setFontSize(9);
  doc.text(`Generated: ${timestamp || new Date().toLocaleString()}`, MARGIN, y + 24);

  // CTAS badge
  const ctasColor = CTAS_COLORS[assessment?.ctasLevel] || [160, 174, 192];
  doc.setFillColor(...ctasColor);
  doc.roundedRect(pageWidth - 65, 8, 50, 28, 3, 3, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text('CTAS Level', pageWidth - 55, 19);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(String(assessment?.ctasLevel ?? 'N/A'), pageWidth - 43, 32);

  y = 55;
  doc.setDrawColor(...TEAL);
  doc.setLineWidth(0.5);
  doc.line(MARGIN, y, pageWidth - MARGIN, y);
  y += 10;

  // Symptom Summary
  y = heading(doc, 'SYMPTOM SUMMARY', y);
  body(doc);
  y = writeWrapped(doc, assessment?.symptomSummary || transcript || 'No symptom data available.', y);
  y += 10;

  // AI Assessment
  y = heading(doc, 'AI ASSESSMENT', y);
  doc.setTextColor(...GRAY);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'bold');
  y = ensureSpace(doc, y, 10);
  doc.text(`Suggested CTAS Level: ${assessment?.ctasLevel ?? 'N/A'} - ${CTAS_NAMES[assessment?.ctasLevel] || ''}`, MARGIN, y);
  y += 7;
  doc.setFont('helvetica', 'normal');
  doc.text(`Care Recommendation: ${assessment?.careRecommendation || 'N/A'}`, MARGIN, y);
  y += 10;

  if (assessment?.reasoning) {
    doc.setFont('helvetica', 'bold');
    y = ensureSpace(doc, y, 10);
    doc.text('Reasoning:', MARGIN, y);
    y += 6;
    body(doc);
    y = writeWrapped(doc, assessment.reasoning, y);
  }

  footer(doc);
  return doc;
}

// ── Visit Summary (walk-in / pharmacy) ──

export function generateVisitSummaryPDF({ transcript, assessment, timestamp }) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  // Header bar
  doc.setFillColor(...TEAL);
  doc.rect(0, 0, pageWidth, 35, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('Rivr - Visit Summary', MARGIN, y + 10);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${timestamp || new Date().toLocaleString()}`, MARGIN, y + 20);

  y = 45;

  // Disclaimer box
  doc.setFillColor(245, 247, 250);
  doc.roundedRect(MARGIN, y, pageWidth - 2 * MARGIN, 20, 3, 3, 'F');
  doc.setTextColor(100, 100, 100);
  doc.setFontSize(9);
  doc.text('This document summarizes an AI-powered pre-assessment. It is not a diagnosis.', MARGIN + 5, y + 8);
  doc.text('Please use this as reference information for your healthcare provider.', MARGIN + 5, y + 14);
  y += 28;

  // Symptoms
  y = heading(doc, 'What I Was Experiencing', y);
  body(doc);
  y = writeWrapped(doc, assessment?.symptomSummary || transcript || 'No symptom data recorded.', y, 5);
  y += 10;

  // AI Assessment
  y = heading(doc, 'AI Assessment Finding', y);
  body(doc);
  y = ensureSpace(doc, y, 10);
  doc.text(`Recommendation: ${assessment?.careRecommendation || 'Consult a healthcare provider'}`, MARGIN + 5, y);
  y += 8;

  if (assessment?.reasoning) {
    y = writeWrapped(doc, assessment.reasoning, y, 5);
  }

  // Footer
  const footerY = doc.internal.pageSize.getHeight() - 20;
  doc.setFontSize(7);
  doc.setTextColor(...LIGHT_GRAY);
  doc.text('Generated by Rivr (rivr.ca) — AI-powered pre-assessment. Not a medical diagnosis.', MARGIN, footerY);

  return doc;
}

export function downloadPDF(doc, filename) {
  doc.save(filename);
}
