import { useState, useEffect } from 'react';
import { AlertTriangle, ShieldCheck } from 'lucide-react';

export default function Disclaimer({ onAccept }) {
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const timer = setTimeout(() => setIsVisible(true), 100);
    return () => clearTimeout(timer);
  }, []);

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-dark-bg/80 backdrop-blur-xl">
      <div
        className={`w-full max-w-md glass rounded-2xl shadow-2xl overflow-hidden transition-all duration-500 transform ${
          isVisible ? 'opacity-100 translate-y-0 scale-100' : 'opacity-0 translate-y-8 scale-95'
        }`}
      >
        {/* Header */}
        <div className="p-6 flex flex-col items-center text-center border-b border-white/5"
          style={{ background: 'linear-gradient(180deg, rgba(245,101,101,0.1) 0%, transparent 100%)' }}>
          <div className="w-16 h-16 rounded-full flex items-center justify-center mb-4 animate-pulse-ring"
            style={{ backgroundColor: 'rgba(245,101,101,0.12)', border: '1px solid rgba(245,101,101,0.3)' }}>
            <AlertTriangle className="w-8 h-8 text-danger" />
          </div>
          <h2 className="text-xl font-bold text-white mb-2">Important Medical Disclaimer</h2>
          <p className="text-danger text-sm font-medium">Please read carefully before proceeding</p>
        </div>

        {/* Content */}
        <div className="p-6 space-y-4 text-sm text-text-light leading-relaxed">
          <p>
            <strong className="text-white">Rivr is an AI-powered triage demonstration tool.</strong> It is designed to simulate preliminary health assessments based on the Canadian Triage and Acuity Scale (CTAS).
          </p>
          <ul className="space-y-2 list-disc pl-5">
            <li>This tool <span className="text-white font-medium">does not provide medical diagnoses</span> or professional medical advice.</li>
            <li>The assessment provided is generated by artificial intelligence and <span className="text-white font-medium">may contain errors</span>.</li>
            <li>Do not use this tool as a substitute for professional medical care.</li>
          </ul>

          <div className="p-4 rounded-xl flex items-start gap-3"
            style={{ backgroundColor: 'rgba(20,184,166,0.08)', border: '1px solid rgba(20,184,166,0.2)' }}>
            <ShieldCheck className="w-5 h-5 text-primary shrink-0 mt-0.5" />
            <p className="text-xs text-white/90">
              If you are experiencing a life-threatening emergency, such as severe chest pain, extreme difficulty breathing, or sudden weakness/numbness, <strong className="text-primary font-bold">call 911 immediately</strong>.
            </p>
          </div>
        </div>

        {/* Action */}
        <div className="p-6 border-t border-white/5">
          <button
            onClick={() => {
              setIsVisible(false);
              setTimeout(onAccept, 400);
            }}
            className="w-full py-4 rounded-xl bg-gradient-to-r from-primary to-accent text-white font-bold text-lg
              transition-all duration-300 shadow-lg shadow-primary/20 cursor-pointer hover:opacity-90"
          >
            I Understand & Agree
          </button>
        </div>
      </div>
    </div>
  );
}
